# Generated by Django 2.2 on 2019-05-10 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190504_0033'),
        ('users', '0002_auto_20190504_2100'),
    ]

    operations = [
    ]
