# Generated by Django 2.2 on 2019-05-11 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_merge_20190510_1112'),
        ('users', '0003_merge_20190511_0241'),
    ]

    operations = [
    ]
