# Generated by Django 2.2 on 2019-05-04 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('discussion', 'Discussion'), ('question', 'Question'), ('solved', 'Solved'), ('feedback', 'Feedback'), ('article', 'Article')], default='question', max_length=10),
        ),
    ]
