# Generated by Django 2.2 on 2019-05-04 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_post_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('discussion', 'Discussion'), ('question', 'Question'), ('feedback', 'Feedback'), ('solved', 'Solved'), ('article', 'Article')], default='question', max_length=10),
        ),
    ]
