# Generated by Django 2.2 on 2019-05-10 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0010_auto_20190509_2227'),
        ('forum', '0002_post_like'),
    ]

    operations = [
    ]
