# Generated by Django 2.2 on 2019-05-11 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0013_auto_20190511_0301'),
        ('forum', '0011_merge_20190510_1112'),
    ]

    operations = [
    ]
