# Generated by Django 2.2 on 2019-05-11 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0014_merge_20190511_1022'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='text',
            new_name='reply',
        ),
    ]
